/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Меню №1: Только для Райтапов (берет всё из папки docs/writeups)
  writeupsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'writeups', 
    },
  ],

  // Меню №2: Только для Скриптов (берет всё из папки docs/scripts)
  scriptsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'scripts',
    },
  ],
};

export default sidebars;