/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Это заставит движок самому сканировать папку docs и строить дерево
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', 
    },
  ],
};

export default sidebars;